import { Button, Text } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => (
  <div className={styles.container}>
    <Head>
      <title>ウマ娘サポカ編成ツール</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>

    <main className={styles.main}>
      <Button>Chakra UI Button</Button>
      <Text>hello</Text>
    </main>
  </div>
);

export default Home;
